#!/usr/bin/env python3
import json
import sys
import os
import glob


def main():
    files = [v for v in sys.argv if ".ipynb" in v]
    for fname in files:
        print("Converting ", fname)

        with open(fname, 'r') as fi:
            content = fi.read()

        structure = json.loads(content)
        cells = structure['cells']
        basefname = fname.replace('.ipynb', '.py')
        # split('/')[-1]
        with open(basefname, 'w') as fi:
            for cell in cells:
                if cell['cell_type'] == "code":
                    source = cell["source"]
                    source = ["# " + v if v.startswith("%")
                              else v for v in source]
                    source = [v.replace("\n%", "\n")
                              for v in source]
                    fi.write("".join(source))

                fi.write('\n')  # end line on cell

if __name__=='__main__':
    main()

